# Generated by Django 5.0.6 on 2024-08-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Laboratory', 'Laboratory'), ('Other', 'Other')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('free', 'Free')], default='free', max_length=10)),
                ('room_type', models.CharField(choices=[('private', 'Private'), ('icu', 'ICU'), ('general', 'General')], max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sickbay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickbay_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('free', 'Free')], default='free', max_length=10)),
                ('capacity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_occupancy', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('room', 'Room'), ('sickbay', 'Sickbay')], max_length=10)),
                ('date_allocated', models.DateTimeField(auto_now_add=True)),
                ('date_released', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.room')),
                ('sickbay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.sickbay')),
            ],
        ),
    ]
