# Generated by Django 5.0.6 on 2024-08-07 22:54

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('case_manager', 'Case Manager'), ('laboratorist', 'Laboratorist'), ('accountant', 'Accountant'), ('hr_manager', 'Human Resource Manager')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('recent_training', models.TextField(blank=True, null=True)),
                ('performance_reviews', models.TextField(blank=True, null=True)),
                ('current_account_load', models.IntegerField(default=0)),
                ('recent_trainings', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('case_load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_instructions', models.TextField(blank=True, null=True)),
                ('follow_up_appointments', models.TextField(blank=True, null=True)),
                ('discharge_status', models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('treatment_summary', models.TextField(blank=True, null=True)),
                ('medication_at_discharge', models.TextField(blank=True, null=True)),
                ('condition_at_discharge', models.TextField(blank=True, null=True)),
                ('discharge_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('support_services_required', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('medical_license_number', models.CharField(max_length=50)),
                ('board_certifications', models.TextField()),
                ('current_patient_load', models.IntegerField(default=0)),
                ('appointment_schedule', models.TextField(blank=True, null=True)),
                ('recent_treatments', models.TextField(blank=True, null=True)),
                ('recent_training', models.TextField(blank=True, null=True)),
                ('performance_reviews', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('rather_not_say', 'Rather Not Say')], max_length=20)),
                ('hire_date', models.DateField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='staff/certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='HRManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('recent_training', models.TextField(blank=True, null=True)),
                ('performance_reviews', models.TextField(blank=True, null=True)),
                ('team_size_managed', models.IntegerField(default=0)),
                ('current_projects', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('current_lab_load', models.IntegerField(default=0)),
                ('lab_specialization', models.CharField(choices=[('microbiology', 'Microbiology'), ('chemistry', 'Chemistry'), ('pathology', 'Pathology'), ('hematology', 'Hematology'), ('immunology', 'Immunology'), ('tansfusion_medicine', 'Transfusion medicine'), ('toxicology', 'Toxicology'), ('molecular_diagnostics', 'Molecular Diagnostics')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('current_patient_load', models.IntegerField(default=0)),
                ('recent_trainings', models.TextField(blank=True, null=True)),
                ('performance_reviews', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('medical_history', models.TextField()),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('health_habits', models.TextField(blank=True, null=True)),
                ('disease', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Treatment', 'In Treatment'), ('New Patient', 'New Patient'), ('Recovered', 'Recovered'), ('discharged', 'Discharged')], max_length=70)),
                ('document', models.FileField(blank=True, null=True, upload_to='patients/documents')),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.TextField(blank=True, null=True)),
                ('pharmacy_license_number', models.CharField(max_length=100)),
                ('current_medication_load', models.CharField(max_length=100)),
                ('license_expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_hired', models.DateField()),
                ('responsibilities', models.TextField()),
            ],
            options={
                'verbose_name': 'Representative',
                'verbose_name_plural': 'Representatives',
            },
        ),
    ]
