# Generated by Django 5.0.6 on 2024-08-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('case_management', '0001_initial'),
        ('facilities', '0001_initial'),
        ('human_resource', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='casemanager',
            name='assigned_cases',
            field=models.ManyToManyField(blank=True, related_name='case_managers', to='case_management.case'),
        ),
        migrations.AddField(
            model_name='casemanager',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='casemanager',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='discharge_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='casemanager',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_manager_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_manager_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, related_name='assigned_laboratorists', to='laboratory.labtest'),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorist_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='facilities.room'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='accounts.patient'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.shift'),
        ),
        migrations.AddField(
            model_name='representative',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.department'),
        ),
    ]
