# Generated by Django 5.0.6 on 2024-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_budget_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(default='Some Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='financials/financial_reports/'),
        ),
    ]
